### ISSUE TITLE
For anyone who's interested, here's a similar plugin for Sublime Text 3

### ISSUE THREAD

**Issue by uduse** [Cycododge/SublimeText-GameMaker-Plugin#1]
[Click Me](https://github.com/Uduse/Sublime-GameMaker-Studio-Language-Bundle)

**Comment by coppolaemilio** [comment]
@Uduse Hello there! I will add it to the readme 👍

**Comment by Cycododge** [comment]
Updated the [readme.md](https://github.com/Cycododge/SublimeText-GameMaker-Plugin/commit/40c911c32286b9287ad95ce02ac804dd31e7b310) to reference your implementation. Thank you for sharing!
